parameters:
  BuildPlatform: ''

steps:
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: 'projects/openttd_vs142.sln'
    platform: ${{ parameters.BuildPlatform }}
    configuration: ${{ parameters.BuildConfiguration }}
    maximumCpuCount: true
